#include "UIA_EventIdsWrapper.h"
#include "UIA_PatternIdsWrapper.h"
#include "UIA_PropertyIdsWrapper.h"
#include "AutomationElementModeWrapper.h"
#include "TreeScopeWrapper.h"
#include "SafeArrayWrapper.h"
#include "RectWrapper.h"

#include "IUnknownWrapper.h"
#include "IUIAutomationWrapper.h"
#include "IUIAutomationElementWrapper.h"
#include "IUIAutomationConditionWrapper.h"
#include "IUIAutomationElementArrayWrapper.h"
#include "IUIAutomationTreeWalkerWrapper.h"
#include "IUIAutomationCacheRequestWrapper.h"
#include "IUIAutomationProxyFactoryMappingWrapper.h"

#include "IUIAutomationEventHandlerWrapper.h"
#include "IUIAutomationFocusChangedEventHandlerWrapper.h"
#include "IUIAutomationPropertyChangedEventHandlerWrapper.h"
#include "IUIAutomationStructureChangedEventHandlerWrapper.h"
