{
  "targets": [
    {
      "target_name": "Automation",
      "cflags!": [ "-fno-exceptions" ],
      "cflags_cc!": [ "-fno-exceptions" ],
      "msvs_settings": {
        "VCCLCompilerTool": { "ExceptionHandling": 1 },
      },
      "sources": [ 
            "AutomationAddon.cc",

            "enumerations/AnnotationTypeIdsWrapper.cc",
            "enumerations/AttributeIdsWrapper.cc",
            "enumerations/ControlTypeIdsWrapper.cc",
            "enumerations/DockPositionsWrapper.cc",
            "enumerations/ElementModesWrapper.cc",
            "enumerations/EventIdsWrapper.cc",
            "enumerations/ExpandCollapseStatesWrapper.cc",
            "enumerations/OrientationTypesWrapper.cc",
            "enumerations/PatternIdsWrapper.cc",
            "enumerations/PropertyIdsWrapper.cc",
            "enumerations/ProviderOptionsWrapper.cc",
            "enumerations/RowOrColumnMajorWrapper.cc",
            "enumerations/StyleIdsWrapper.cc",
            "enumerations/ScrollAmountsWrapper.cc",
            "enumerations/SupportedTextSelectionsWrapper.cc",
            "enumerations/SynchronizedInputTypesWrapper.cc",
            "enumerations/TextPatternRangeEndpointWrapper.cc",
            "enumerations/TextUnitsWrapper.cc",
            "enumerations/ToggleStatesWrapper.cc",
            "enumerations/TreeScopesWrapper.cc",
            "enumerations/WindowInteractionStatesWrapper.cc",
            "enumerations/WindowVisualStatesWrapper.cc",
            "enumerations/ZoomUnitsWrapper.cc",

            "utilities/AutomationEventHandler.cc",
            "utilities/FocusChangedEventHandler.cc",
            "utilities/PropertyChangedEventHandler.cc",
            "utilities/StructureChangedEventHandler.cc",
            "utilities/Functions.cc",

            "wrappers/RectWrapper.cc",
            "wrappers/IUnknownWrapper.cc",

            # "wrappers/IAccessibleWrapper.cc",
            "wrappers/IUIAutomationElementWrapper.cc" ,
            "wrappers/IUIAutomationWrapper.cc", 
            "wrappers/IUIAutomationConditionWrapper.cc",
            "wrappers/IUIAutomationElementArrayWrapper.cc",
            "wrappers/IUIAutomationTreeWalkerWrapper.cc",
            "wrappers/IUIAutomationCacheRequestWrapper.cc", 
            "wrappers/IUIAutomationProxyFactoryMappingWrapper.cc",
            "wrappers/IUIAutomationFocusChangedEventHandlerWrapper.cc",
            "wrappers/IUIAutomationEventHandlerWrapper.cc",
            "wrappers/IUIAutomationPropertyChangedEventHandlerWrapper.cc",
            "wrappers/IUIAutomationStructureChangedEventHandlerWrapper.cc",

            "patterns/IUIAutomationTextRangeWrapper.cc",
            "patterns/IUIAutomationAnnotationPatternWrapper.cc",
            "patterns/IUIAutomationDockPatternWrapper.cc",
            "patterns/IUIAutomationDragPatternWrapper.cc",
            "patterns/IUIAutomationDropTargetPatternWrapper.cc",
            "patterns/IUIAutomationExpandCollapsePatternWrapper.cc",
            "patterns/IUIAutomationGridItemPatternWrapper.cc",
            "patterns/IUIAutomationGridPatternWrapper.cc",
            "patterns/IUIAutomationInvokePatternWrapper.cc",
            "patterns/IUIAutomationItemContainerPatternWrapper.cc",
            "patterns/IUIAutomationLegacyIAccessiblePatternWrapper.cc",
            "patterns/IUIAutomationMultipleViewPatternWrapper.cc",
            "patterns/IUIAutomationRangeValuePatternWrapper.cc",
            "patterns/IUIAutomationScrollItemPatternWrapper.cc",
            "patterns/IUIAutomationScrollPatternWrapper.cc",
            "patterns/IUIAutomationSelectionItemPatternWrapper.cc",
            "patterns/IUIAutomationSelectionPatternWrapper.cc",
            "patterns/IUIAutomationSelectionPattern2Wrapper.cc",
            "patterns/IUIAutomationSpreadsheetItemPatternWrapper.cc",
            "patterns/IUIAutomationSpreadsheetPatternWrapper.cc", 
            "patterns/IUIAutomationStylesPatternWrapper.cc",
            "patterns/IUIAutomationSynchronizedInputPatternWrapper.cc",
            "patterns/IUIAutomationTableItemPatternWrapper.cc",
            "patterns/IUIAutomationTablePatternWrapper.cc",
            "patterns/IUIAutomationTextChildPatternWrapper.cc",
            "patterns/IUIAutomationTextEditPatternWrapper.cc",
            "patterns/IUIAutomationTextPatternWrapper.cc",
            "patterns/IUIAutomationTextPattern2Wrapper.cc",
            "patterns/IUIAutomationTogglePatternWrapper.cc",
            "patterns/IUIAutomationTransformPatternWrapper.cc",
            "patterns/IUIAutomationTransformPattern2Wrapper.cc",
            "patterns/IUIAutomationValuePatternWrapper.cc",
            "patterns/IUIAutomationVirtualizedItemPatternWrapper.cc",
            "patterns/IUIAutomationWindowPatternWrapper.cc",
      ],
      "include_dirs": ["<!(node -p \"require('node-addon-api').include_dir\")"],
      "libraries" : [
        "uiautomationcore.lib",
      ]
    }
  ]
}