{
  "targets": [
    {
      "target_name": "Automation",
      "cflags!": [ "-fno-exceptions" ],
      "cflags_cc!": [ "-fno-exceptions" ],
      "msvs_settings": {
        "VCCLCompilerTool": { "ExceptionHandling": 1 },
      },
      "sources": [ 
            "AutomationAddon.cc",
            "enumerations/AnnotationTypeIdsWrapper.cc",
            "enumerations/AttributeIdsWrapper.cc",
            "enumerations/ControlTypeIdsWrapper.cc",
            "enumerations/DockPositionsWrapper.cc",
            "enumerations/ElementModesWrapper.cc",
            "enumerations/EventIdsWrapper.cc",
            "enumerations/ExpandCollapseStatesWrapper.cc",
            "enumerations/OrientationTypesWrapper.cc",
            "enumerations/PatternIdsWrapper.cc",
            "enumerations/PropertyIdsWrapper.cc",
            "enumerations/ProviderOptionsWrapper.cc",
            "enumerations/RowOrColumnMajorWrapper.cc",
            "enumerations/StyleIdsWrapper.cc",
            "enumerations/SupportedTextSelectionsWrapper.cc",
            "enumerations/SynchronizedInputTypesWrapper.cc",
            "enumerations/TextPatternRangeEndpointWrapper.cc",
            "enumerations/TextUnitsWrapper.cc",
            "enumerations/ToggleStatesWrapper.cc",
            "enumerations/TreeScopesWrapper.cc",
            "enumerations/WindowInteractionStatesWrapper.cc",
            "enumerations/WindowVisualStatesWrapper.cc",
            "enumerations/ZoomUnitsWrapper.cc",


            "wrappers/RectWrapper.cc",
            "wrappers/IUnknownWrapper.cc",

            # "wrappers/IAccessibleWrapper.cc",
            "wrappers/IUIAutomationElementWrapper.cc" ,
            "wrappers/IUIAutomationWrapper.cc", 
            "wrappers/IUIAutomationConditionWrapper.cc",
            "wrappers/IUIAutomationElementArrayWrapper.cc",
            "wrappers/IUIAutomationTreeWalkerWrapper.cc",
            "wrappers/IUIAutomationCacheRequestWrapper.cc", 
            "wrappers/IUIAutomationProxyFactoryMappingWrapper.cc",
            "wrappers/IUIAutomationFocusChangedEventHandlerWrapper.cc",
            "wrappers/IUIAutomationEventHandlerWrapper.cc",
            "wrappers/IUIAutomationPropertyChangedEventHandlerWrapper.cc",
            "wrappers/IUIAutomationStructureChangedEventHandlerWrapper.cc",

            "utilities/AutomationEventHandler.cc",
            "utilities/FocusChangedEventHandler.cc",
            "utilities/PropertyChangedEventHandler.cc",
            "utilities/StructureChangedEventHandler.cc",
            "utilities/Functions.cc",

            "providers/IRawElementProviderSimpleWrapper.cc",
            "providers/ITextRangeProviderWrapper.cc",

            "providers/IAnnotationProviderWrapper.cc",
            "providers/IDockProviderWrapper.cc",
            "providers/IDragProviderWrapper.cc",
            "providers/IDropTargetProviderWrapper.cc",
            "providers/IExpandCollapseProviderWrapper.cc",
            "providers/IGridItemProviderWrapper.cc",
            "providers/IGridProviderWrapper.cc",
            "providers/IInvokeProviderWrapper.cc",
            "providers/IItemContainerProviderWrapper.cc",
            "providers/ILegacyIAccessibleProviderWrapper.cc",
            "providers/IMultipleViewProviderWrapper.cc",
            "providers/IRangeValueProviderWrapper.cc",
            "providers/IScrollItemProviderWrapper.cc",
            "providers/IScrollProviderWrapper.cc",
            "providers/ISelectionItemProviderWrapper.cc",
            "providers/ISelectionProviderWrapper.cc",
            "providers/ISelectionProvider2Wrapper.cc",
            "providers/ISpreadsheetItemProviderWrapper.cc",
            "providers/ISpreadsheetProviderWrapper.cc", 
            "providers/IStylesProviderWrapper.cc",
            "providers/ISynchronizedInputProviderWrapper.cc",
            "providers/ITableItemProviderWrapper.cc",
            "providers/ITableProviderWrapper.cc",
            "providers/ITextChildProviderWrapper.cc",
            "providers/ITextEditProviderWrapper.cc",
            "providers/ITextProviderWrapper.cc",
            "providers/ITextProvider2Wrapper.cc",
            "providers/IToggleProviderWrapper.cc",
            "providers/ITransformProviderWrapper.cc",
            "providers/ITransformProvider2Wrapper.cc",
            "providers/IValueProviderWrapper.cc",
            "providers/IVirtualizedItemProviderWrapper.cc",
            "providers/IWindowProviderWrapper.cc",
      ],
      "include_dirs": ["<!(node -p \"require('node-addon-api').include_dir\")"],
      "libraries" : [
        "uiautomationcore.lib",
      ]
    }
  ]
}