#pragma once

#include "AutomationAddon.h"
#include "IUIAutomationWrapper.h"
#include "IUIAutomationElementWrapper.h"
#include "UIA_PropertyIdsWrapper.h"
#include "TreeScopeWrapper.h"
#include "IUIAutomationConditionWrapper.h"
#include "RectWrapper.h"
#include "IUIAutomationElementArrayWrapper.h"
#include "IUIAutomationTreeWalkerWrapper.h"
#include "IUIAutomationCacheRequestWrapper.h"
#include "IUIAutomationProxyFactoryMappingWrapper.h"
#include "IUIAutomationEventHandlerWrapper.h"
#include "IUnknownWrapper.h"
#include "UIA_EventIdsWrapper.h"